// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQXaaSvP5yTzdukd4lXRJg7-IbDL2eK8I',
    appId: '1:390282911286:web:3416ad918fb69bbcf54297',
    messagingSenderId: '390282911286',
    projectId: 'individualsaru',
    authDomain: 'individualsaru.firebaseapp.com',
    storageBucket: 'individualsaru.appspot.com',
    measurementId: 'G-CG2E1RR9C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXSr7cmGUz5khvXjMc8WnQ-9d3pyd7xCw',
    appId: '1:390282911286:android:d2951292bf3aaadff54297',
    messagingSenderId: '390282911286',
    projectId: 'individualsaru',
    storageBucket: 'individualsaru.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5mR6ByDDMNpNk72FWD0xk4n2EV7OXOY',
    appId: '1:390282911286:ios:60d0642af68acb9af54297',
    messagingSenderId: '390282911286',
    projectId: 'individualsaru',
    storageBucket: 'individualsaru.appspot.com',
    iosClientId: '390282911286-ko3a1np6ajena5gkp9viskecm2bv9mhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5mR6ByDDMNpNk72FWD0xk4n2EV7OXOY',
    appId: '1:390282911286:ios:60d0642af68acb9af54297',
    messagingSenderId: '390282911286',
    projectId: 'individualsaru',
    storageBucket: 'individualsaru.appspot.com',
    iosClientId: '390282911286-ko3a1np6ajena5gkp9viskecm2bv9mhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
